### ISSUE TITLE
One Handed Skill

### ISSUE THREAD

**Issue by communityus** [michaelday008/AnyRPGCore#13]
Need One Handed Skill from Skill trainer so we can play with the sword.

**Comment by michaelday008** [comment]
The skill trainer is only for crafting and gathering skills.  The One Hand Sword skill is assigned to the character class so if you want to use it on a certain class, just add it to that class.  I'm not sure what version you are using, but in the Core Game from the github package, that skill is assigned to the Tank specialization.  In the Lost Soul demo game, it's available on the Warrior class.
