### ISSUE TITLE
Add Object Pooling

### ISSUE THREAD

**Issue by michaelday008** [michaelday008/AnyRPGCore#18]
Currently, the combat text is the only thing that is pooled.

This means all objects that are instantiated at run-time are not re-used.  They are created, and permanently destroyed.

This leads to a lot of garbage collection which causes spikes in CPU usage, and dropping frame rates or input and graphic lag.

An object pooling system should be used for instantiation of all objects in the engine.  This will involve a bit of work to ensure that all pooled objects can have their properties reset properly on re-use.

For example, a re-used arrow object should not begin immediately heading toward its last target etc.

**Comment by grannypron** [comment]
This framework looks pretty comprehensive and provides interfaces, hooks for creation/destruction, and general configuration parameters.  In other words, it looks like they have thought out the problem.  MIT license.

https://github.com/GalvanicGames/unity-pooler 

If you agree, a plan of attack might be to drop this in, and then change the combat message text implementation as a first step.  Regression test. Then, identify good candidates for pooling.  Then apply the interface to those candidates one at a time.

**Comment by michaelday008** [comment]
Nice find.  I was just going to use this code from Unity Learn, but the one you found looks like it has more configuration options.

https://learn.unity.com/tutorial/introduction-to-object-pooling

https://www.raywenderlich.com/847-object-pooling-in-unity

**Comment by grannypron** [comment]
Yeah it would kinda suck to have to add that component to every prefab

**Comment by grannypron** [comment]
I used a simpler one from  https://github.com/ertanturan/Unity-Object-Pooling

To integrate, one tags and adds their prefab to an enum  :/   and then adds a game object to the root specifying that tag.  

Here's a diff to see a basic implementation for CombatText pooling.   I took out his dependency injection drek:

https://github.com/michaelday008/AnyRPGCore/compare/master...grannypron:18-objectpooling

If you like it, lmk and I can polish it up.

**Comment by grannypron** [comment]
![image](https://user-images.githubusercontent.com/19980049/109343049-bbda1500-783a-11eb-9919-547e17c6e049.png)

Simple setup of the pooler

**Comment by grannypron** [comment]
![image](https://user-images.githubusercontent.com/19980049/109343140-d90ee380-783a-11eb-9040-eacf04ef0e63.png)
Simple setup of the pooler

**Comment by michaelday008** [comment]
Thanks for looking into this.  After further review, the two poolers I linked were far too basic for what I need.

That one you found has some good features, but in some respects I think it's over-engineered, and in some, missing the flexibility I'm looking for in this update. I may use some of the code, but decided to just write a custom object pooler.  You can see the types of features that are needed for it to just work out of the box for everyone without adding enums or tags.

![image](https://user-images.githubusercontent.com/49324924/109436038-67699d80-79d2-11eb-84c3-23fe68075b27.png)

**Comment by michaelday008** [comment]
Released with 0.11a
