### ISSUE TITLE
Third Party Controller Support

### ISSUE THREAD

**Issue by SickaGamer** [michaelday008/AnyRPGCore#2]
I am wondering if there would be an easy way to integrate third party controllers such as Invector Shooter Template.  I also know a lot of the Unity community also uses Ootti or UFPS.

**Comment by michaelday008** [comment]
At this point the controller is still very much a work in progress.  I'm still making a lot of core changes to it (such as all the recent refactoring to support mounts).

Third party integration is likely a while away until I get some other stuff handled like sliding down slopes, flying, swimming, following ground contours in all directions (not just forward and backward) etc.

It is definitely something I would like to integrate in the future though, so I will keep this ticket on the backlog for now.

**Comment by michaelday008** [comment]
Third party controller support is now released.  The Object Message Controller is extensible enough to use for any third party integration with no requirement to write code.  Template for Invector Basic Movement is included.  Tutorial is available on YouTube.
