### ISSUE TITLE
New game wizard

### ISSUE THREAD

**Issue by grannypron** [michaelday008/AnyRPGCore#20]
From #contribute-code:

"[ OPEN ] The engine would be more user friendly with a new game wizard.  It should create:
-New folder in root of project with game name
-Resources Folder with subdirectory structure for all scriptableobjects
-A new scene called <GameName>Game that contains the UMA_DCS prefab and a variant of the GameManager prefab with the game name, version, Resources folder name, already configured.
-A new scene called FirstScene (or a user provided name) that is loaded automatically when a new game is started.  This scene can be completely empty or just have a terrain / plane so the character doesn't fall through the map on load
See the invector new character creator for an example of a new thing creation screen popup."

**Comment by michaelday008** [comment]
This has been manually added using the code from #21
