### ISSUE TITLE
Third Party/AnyRPG Mounts Integration

### ISSUE THREAD

**Issue by SickaGamer** [michaelday008/AnyRPGCore#4]
This would be either an in house solution or something that can integrate with Malbers Horse Animation Pro.

**Comment by michaelday008** [comment]
I've fixed up a lot of the issues with the mount animation speed.

Have a look at the final few minutes of https://www.youtube.com/watch?v=opG-Ih6HwRw and let me know if the mounted motion in there is OK.

**Comment by michaelday008** [comment]
Mounts can now be used with the native controller, or with the invector controller (although when riding it has to use the default controller).
