### ISSUE TITLE
Master and music volume setting ignored

### ISSUE THREAD

**Issue by nothingTVatYT** [michaelday008/AnyRPGCore#42]
When you start a game the master and music volume in the settings (player preferences) are ignored by the audio manager though the UI shows the saved setting.

**Comment by michaelday008** [comment]
// due to "intended" but not officially documented behavior, audio updates will be overwritten if called in Awake() so they must be called in Start()
            // https://fogbugz.unity3d.com/default.asp?1197165_nik4gg1io942ae13#bugevent_1071843210

This is fixed now.
