### ISSUE TITLE
repeatable collect quest can be turned in over and over

### ISSUE THREAD

**Issue by nothingTVatYT** [michaelday008/AnyRPGCore#46]
It looks like a check is missing in the most recent changes so that you can turn in a repeatable item collect quest even if you don't have any required items.

**Comment by michaelday008** [comment]
It looks like this is due to the way that objective completion status is permanently saved.  The overhaul of the quest system to include multi-step quests is now in progress and will include a few test quests specifically for this use case to ensure it's working properly.

**Comment by michaelday008** [comment]
This is now fixed in the latest master
