### ISSUE TITLE
UMA Assets Easy Integration

### ISSUE THREAD

**Issue by SickaGamer** [michaelday008/AnyRPGCore#5]
An easy way to add UMA slot items as rewards for quests/NPC drops that will work with the UMA player avatar.

**Comment by michaelday008** [comment]
Have a look at 
https://www.youtube.com/watch?v=opG-Ih6HwRw (UMA rewards as drops in dungeon)
and 
https://www.youtube.com/watch?v=gprMAl9vLiA (making new UMA armor).

Let me know if that was what you were looking for

**Comment by michaelday008** [comment]
All equipment has the option to have UMA recipes associated with it.
