### ISSUE TITLE
MiniMap to Open to World Map

### ISSUE THREAD

**Issue by SickaGamer** [michaelday008/AnyRPGCore#6]
Have the system MiniMap open to a full world map by pressing "M" key or something of that nature.

**Comment by michaelday008** [comment]
Currently you can press the "M" key to open the main map any time.  This key can be bound or changed within the keybind options in-game.

You can also click the map icon on the system bar near the main menu and character icons.

I'm going to replace the "M" on the minimap with the same map icon on the system bar and make it clickable soon.  The M was only ever meant to be a placeholder until I found a good map icon, which I have now.

**Comment by michaelday008** [comment]
Added in #25
