### ISSUE TITLE
Further Testing with a custom humanoid character- some errors in the editor

### ISSUE THREAD

**Issue by nigelmerle** [michaelday008/AnyRPGCore#75]
humanoid character spawn in game but I got some errors in the editor: the character idle  but does not walk

**Comment by nigelmerle** [comment]
![Screenshot (190)](https://user-images.githubusercontent.com/17375811/147365110-e590a91b-9036-4ba6-8469-c68e06f1f313.png)

**Comment by nigelmerle** [comment]
![Screenshot (189)](https://user-images.githubusercontent.com/17375811/147365135-c72c1df2-4448-4b15-aaac-e0b060259a2c.png)

**Comment by nigelmerle** [comment]
![Screenshot (191)](https://user-images.githubusercontent.com/17375811/147365393-032ee176-f800-421a-a4b1-c2f005b887b6.png)

**Comment by nigelmerle** [comment]
![Screenshot (192)](https://user-images.githubusercontent.com/17375811/147365672-665e4761-7fe8-4e26-a2cd-8f8f062a2328.png)

**Comment by nigelmerle** [comment]
![Screenshot (188)](https://user-images.githubusercontent.com/17375811/147365790-e72d8c35-a7a7-48bc-8fc2-8c2dfee627b9.png)

**Comment by nigelmerle** [comment]
In the gamemanager: 

i tried defaultumaplayer - it works
i tried defaultplayer- it doesnt work

**Comment by nigelmerle** [comment]
PlayerUnitFrame.UnitFrameController.GetFollowTarget(): Could not find targetBone: Head
UnityEngine.Debug:LogWarning (object)
AnyRPG.UnitFrameController:GetFollowTarget () (at Assets/AnyRPG/Core/System/Scripts/UI/PanelControllers/UnitFrameController.cs:435)
AnyRPG.UnitFrameController:HandleTargetReady () (at Assets/AnyRPG/Core/System/Scripts/UI/PanelControllers/UnitFrameController.cs:218)
AnyRPG.UnitFrameController:TargetInitialization () (at Assets/AnyRPG/Core/System/Scripts/UI/PanelControllers/UnitFrameController.cs:194)
AnyRPG.UnitFrameController:SetTarget (AnyRPG.BaseNamePlateController) (at Assets/AnyRPG/Core/System/Scripts/UI/PanelControllers/UnitFrameController.cs:265)
AnyRPG.UIManager:ProcessPlayerUnitSpawn () (at Assets/AnyRPG/Core/System/Scripts/GameManager/UIManagers/UIManager.cs:970)
AnyRPG.UIManager:HandlePlayerUnitSpawn (string,AnyRPG.EventParamProperties) (at Assets/AnyRPG/Core/System/Scripts/GameManager/UIManagers/UIManager.cs:837)
AnyRPG.SystemEventManager:TriggerEvent (string,AnyRPG.EventParamProperties) (at Assets/AnyRPG/Core/System/Scripts/GameManager/SystemEventManager.cs:64)
AnyRPG.PlayerManager:HandlePlayerUnitSpawn () (at Assets/AnyRPG/Core/System/Scripts/GameManager/PlayerManager.cs:468)
AnyRPG.PlayerManager:SpawnPlayerUnit (UnityEngine.Vector3) (at Assets/AnyRPG/Core/System/Scripts/GameManager/PlayerManager.cs:413)
AnyRPG.PlayerManager:SpawnPlayerUnit () (at Assets/AnyRPG/Core/System/Scripts/GameManager/PlayerManager.cs:352)
AnyRPG.PlayerManager:HandleLevelLoad (string,AnyRPG.EventParamProperties) (at Assets/AnyRPG/Core/System/Scripts/GameManager/PlayerManager.cs:241)
AnyRPG.SystemEventManager:TriggerEvent (string,AnyRPG.EventParamProperties) (at Assets/AnyRPG/Core/System/Scripts/GameManager/SystemEventManager.cs:64)
AnyRPG.LevelManager:PerformLevelLoadActivities () (at Assets/AnyRPG/Core/System/Scripts/GameManager/LevelManager.cs:302)
AnyRPG.LevelManager:OnLoadLevel (UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode) (at Assets/AnyRPG/Core/System/Scripts/GameManager/LevelManager.cs:225)
UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded (UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode)

**Comment by nigelmerle** [comment]
Coroutine couldn't be started because the the game object 'PlayerUnitFrame' is inactive!
UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
AnyRPG.UnitFrameController:HandleTargetReady () (at Assets/AnyRPG/Core/System/Scripts/UI/PanelControllers/UnitFrameController.cs:225)
AnyRPG.UnitFrameController:TargetInitialization () (at Assets/AnyRPG/Core/System/Scripts/UI/PanelControllers/UnitFrameController.cs:194)
AnyRPG.UnitFrameController:SetTarget (AnyRPG.BaseNamePlateController) (at Assets/AnyRPG/Core/System/Scripts/UI/PanelControllers/UnitFrameController.cs:265)
AnyRPG.UIManager:ProcessPlayerUnitSpawn () (at Assets/AnyRPG/Core/System/Scripts/GameManager/UIManagers/UIManager.cs:970)
AnyRPG.UIManager:HandlePlayerUnitSpawn (string,AnyRPG.EventParamProperties) (at Assets/AnyRPG/Core/System/Scripts/GameManager/UIManagers/UIManager.cs:837)
AnyRPG.SystemEventManager:TriggerEvent (string,AnyRPG.EventParamProperties) (at Assets/AnyRPG/Core/System/Scripts/GameManager/SystemEventManager.cs:64)
AnyRPG.PlayerManager:HandlePlayerUnitSpawn () (at Assets/AnyRPG/Core/System/Scripts/GameManager/PlayerManager.cs:468)
AnyRPG.PlayerManager:SpawnPlayerUnit (UnityEngine.Vector3) (at Assets/AnyRPG/Core/System/Scripts/GameManager/PlayerManager.cs:413)
AnyRPG.PlayerManager:SpawnPlayerUnit () (at Assets/AnyRPG/Core/System/Scripts/GameManager/PlayerManager.cs:352)
AnyRPG.PlayerManager:HandleLevelLoad (string,AnyRPG.EventParamProperties) (at Assets/AnyRPG/Core/System/Scripts/GameManager/PlayerManager.cs:241)
AnyRPG.SystemEventManager:TriggerEvent (string,AnyRPG.EventParamProperties) (at Assets/AnyRPG/Core/System/Scripts/GameManager/SystemEventManager.cs:64)
AnyRPG.LevelManager:PerformLevelLoadActivities () (at Assets/AnyRPG/Core/System/Scripts/GameManager/LevelManager.cs:302)
AnyRPG.LevelManager:OnLoadLevel (UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode) (at Assets/AnyRPG/Core/System/Scripts/GameManager/LevelManager.cs:225)
UnityEngine.SceneManagement.SceneManager:Internal_SceneLoaded (UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode)

**Comment by nigelmerle** [comment]
NullReferenceException: Object reference not set to an instance of an object
AnyRPG.UnitFrameController.SubscribeToTargetReady () (at Assets/AnyRPG/Core/System/Scripts/UI/PanelControllers/UnitFrameController.cs:205)
AnyRPG.UnitFrameController.TargetInitialization () (at Assets/AnyRPG/Core/System/Scripts/UI/PanelControllers/UnitFrameController.cs:197)
AnyRPG.UnitFrameController.SetTarget (AnyRPG.BaseNamePlateController namePlateController) (at Assets/AnyRPG/Core/System/Scripts/UI/PanelControllers/UnitFrameController.cs:265)
AnyRPG.UIManager.ProcessPlayerUnitSpawn () (at Assets/AnyRPG/Core/System/Scripts/GameManager/UIManagers/UIManager.cs:970)
AnyRPG.UIManager.HandlePlayerUnitSpawn (System.String eventName, AnyRPG.EventParamProperties eventParamProperties) (at Assets/AnyRPG/Core/System/Scripts/GameManager/UIManagers/UIManager.cs:837)
AnyRPG.SystemEventManager.TriggerEvent (System.String eventName, AnyRPG.EventParamProperties eventParam) (at Assets/AnyRPG/Core/System/Scripts/GameManager/SystemEventManager.cs:64)
AnyRPG.PlayerManager.HandlePlayerUnitSpawn () (at Assets/AnyRPG/Core/System/Scripts/GameManager/PlayerManager.cs:468)
AnyRPG.PlayerManager.SpawnPlayerUnit (UnityEngine.Vector3 spawnLocation) (at Assets/AnyRPG/Core/System/Scripts/GameManager/PlayerManager.cs:413)
AnyRPG.PlayerManager.SpawnPlayerUnit () (at Assets/AnyRPG/Core/System/Scripts/GameManager/PlayerManager.cs:352)
AnyRPG.PlayerManager.HandleLevelLoad (System.String eventName, AnyRPG.EventParamProperties eventParamProperties) (at Assets/AnyRPG/Core/System/Scripts/GameManager/PlayerManager.cs:241)
AnyRPG.SystemEventManager.TriggerEvent (System.String eventName, AnyRPG.EventParamProperties eventParam) (at Assets/AnyRPG/Core/System/Scripts/GameManager/SystemEventManager.cs:64)
AnyRPG.LevelManager.PerformLevelLoadActivities () (at Assets/AnyRPG/Core/System/Scripts/GameManager/LevelManager.cs:302)
AnyRPG.LevelManager.OnLoadLevel (UnityEngine.SceneManagement.Scene newScene, UnityEngine.SceneManagement.LoadSceneMode loadSceneMode) (at Assets/AnyRPG/Core/System/Scripts/GameManager/LevelManager.cs:225)
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <0ee480759f3d481d82ada245dc74f9fd>:0)

**Comment by nigelmerle** [comment]
the cast target error controller is back again bro

![Screenshot (193)](https://user-images.githubusercontent.com/17375811/147366565-d90b8c95-00b4-402c-85a4-9191dead10d6.png)

**Comment by michaelday008** [comment]
You have been told multiple times that for user support to use discord.  Github tickets should have exactly one problem per ticket, and should be actual bugs.

The problems here are clearly with your workflow.  If you want to learn how to use AnyRPG, github is not the correct place to do that.

Closing Ticket.
